# CMake generated Testfile for 
# Source directory: /home/gy/DAGSfM_merge_v3/src/base
# Build directory: /home/gy/DAGSfM_merge_v3/src/base
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(base/camera_database_test "camera_database_test")
set_tests_properties(base/camera_database_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;68;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/camera_models_test "camera_models_test")
set_tests_properties(base/camera_models_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;69;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/camera_rig_test "camera_rig_test")
set_tests_properties(base/camera_rig_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;70;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/camera_test "camera_test")
set_tests_properties(base/camera_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;71;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/correspondence_graph_test "correspondence_graph_test")
set_tests_properties(base/correspondence_graph_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;72;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/cost_functions_test "cost_functions_test")
set_tests_properties(base/cost_functions_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;73;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/database_cache_test "database_cache_test")
set_tests_properties(base/database_cache_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;74;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/database_test "database_test")
set_tests_properties(base/database_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;75;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/essential_matrix_utils_test "essential_matrix_utils_test")
set_tests_properties(base/essential_matrix_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;76;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/gps_test "gps_test")
set_tests_properties(base/gps_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;77;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/graph_cut_test "graph_cut_test")
set_tests_properties(base/graph_cut_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;78;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/homography_matrix_utils_test "homography_matrix_utils_test")
set_tests_properties(base/homography_matrix_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;79;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/image_test "image_test")
set_tests_properties(base/image_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;80;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/line_test "line_test")
set_tests_properties(base/line_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;81;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/point2d_test "point2d_test")
set_tests_properties(base/point2d_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;82;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/point3d_test "point3d_test")
set_tests_properties(base/point3d_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;83;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/polynomial_test "polynomial_test")
set_tests_properties(base/polynomial_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;84;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/pose_test "pose_test")
set_tests_properties(base/pose_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;85;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/projection_test "projection_test")
set_tests_properties(base/projection_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;86;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/reconstruction_test "reconstruction_test")
set_tests_properties(base/reconstruction_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;87;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/reconstruction_manager_test "reconstruction_manager_test")
set_tests_properties(base/reconstruction_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;88;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/similarity_transform_test "similarity_transform_test")
set_tests_properties(base/similarity_transform_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;90;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/track_test "track_test")
set_tests_properties(base/track_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;91;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/track_builder_test "track_builder_test")
set_tests_properties(base/track_builder_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;92;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/triangulation_test "triangulation_test")
set_tests_properties(base/triangulation_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;93;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/undistortion_test "undistortion_test")
set_tests_properties(base/undistortion_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;94;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/visibility_pyramid_test "visibility_pyramid_test")
set_tests_properties(base/visibility_pyramid_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;95;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
add_test(base/warp_test "warp_test")
set_tests_properties(base/warp_test PROPERTIES  _BACKTRACE_TRIPLES "/home/gy/DAGSfM_merge_v3/cmake/CMakeHelper.cmake;153;add_test;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;96;COLMAP_ADD_TEST;/home/gy/DAGSfM_merge_v3/src/base/CMakeLists.txt;0;")
